project:
  type: website

website:
  title: "Mysite"
  navbar:
    left:
      - href: index.qmd
        text: Explorateur d'ascension
      - href: around.qmd
        text: Explorateur de lieux
      - href: statistics.qmd
        text: Espace des statistiques
      - about.qmd

format:
  html:
    theme:
      light: [flatly, style.scss]
      dark: [darkly, style.scss]
    css: styles.css
    toc: true


