project:
  type: website

website:
  title: "climb tracker 🚵"
  navbar:
    pinned: true
    left:
      - href: index.qmd
        text: Explorateur d'ascension
      - href: around.qmd
        text: Explorateur de lieux
      - href: statistics.qmd
        text: Espace des statistiques
      - href: about.qmd
        text: A propos

format:
  html:
    theme:
      light: [flatly, style.scss]
      dark: [darkly, style.scss]
    css: [styles.css, leafletban.css]
    toc: true


