project:
  type: website

website:
  title: "Mysite"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: around.qmd
      - href: statistics.qmd
      - about.qmd

format:
  html:
    theme:
      light: [flatly]
    css: styles.css
    toc: true


